### ISSUE TITLE
Clamping in DSP block

### ISSUE THREAD

**Issue by chikashimiyama** [pd-externals/earplug#10]
https://github.com/pd-externals/earplug/blob/0ba02415bbbf6381083442d2f2c90b08cd8e744d/earplug~.c#L64-L69

Those lines just limit the range of input azimuth and elevation. It would be more efficient if this clamping is handled when the object receives a new value.

**Comment by chikashimiyama** [comment]
Check PR #12 and merge if you think it's appropriate 
@danomatika

**Comment by danomatika** [comment]
#12 merged
