### ISSUE TITLE
python script to convert data file to header

### ISSUE THREAD

**Issue by chikashimiyama** [pd-externals/earplug#5]

**Comment by danomatika** [comment]
There is there Perl script which does this already: parse-to-h.pl. Maybe there is a problem in how it did the parsing?

**Comment by chikashimiyama** [comment]
I guess so. the data is completely wrong in .h file.
but if I search for some random number I find in .h in the original .txt file, I can find it. so parsing would be the problem.

**Comment by umlaeute** [comment]
wouldn't it be better to not convert binary data to a text-representation in the first place?

**Comment by chikashimiyama** [comment]
@umlaeute  there are no binary data. both data in .h and .txt are text.

**Comment by chikashimiyama** [comment]
it's text-representation now and the plugin will continue supporting the text file.
